"""Spells data — all combat + world spells, grouped by school and tier.

Inputs:
  catalog/raw/DB/magics/{battle,world}_{day,night,space,primal,neutral}_magics.json
  catalog/raw/Lang/english/texts/magic.json

Output:
  docs/spells-data.js  (window.OE_SPELLS_DATA)

Each spell carries: id, name, icon, school, tier (rank), mana cost per level,
description, magic-type (Recovery / Damage / Buff / Debuff / Summoning / etc),
and whether it's a battle or world spell.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "catalog" / "raw"
OUT_JS = ROOT / "docs" / "spells-data.js"

MAGIC_TOKENS = RAW / "Lang" / "english" / "texts" / "magic.json"

SCHOOL_LABEL = {
    "day":     "Daylight",
    "night":   "Nightshade",
    "space":   "Arcane",
    "primal":  "Primal",
    "neutral": "Neutral",
}

# Display order (matches the Subclasses matrix grouping for schools)
SCHOOL_ORDER = ["day", "night", "space", "primal", "neutral"]


def load_json_strip(path: Path):
    text = path.read_text(encoding="utf-8-sig").lstrip("﻿")
    text = re.sub(r"//[^\n]*", "", text)
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    return json.loads(text)


def load_tokens(path: Path) -> dict[str, str]:
    return {t["sid"]: t["text"] for t in load_json_strip(path).get("tokens", [])}


def collect_spells(tokens: dict[str, str]) -> list[dict]:
    """Walk every magics/*.json file, normalize each spell into a flat dict."""
    out = []
    for p in sorted((RAW / "DB" / "magics").glob("*.json")):
        # Skip test/special/punishment variants — these are not user-castable.
        if any(x in p.name for x in ("test_", "_special", "punishment_")):
            continue
        scope = "world" if p.name.startswith("world_") else "battle"
        for sp in load_json_strip(p).get("array", []):
            if not isinstance(sp, dict) or not sp.get("id"):
                continue
            sid = sp["id"]
            name_sid = sp.get("name") or f"{sid}_name"
            # description can be a list of variants — take the FIRST entry as
            # the display description (matches the in-game tooltip default).
            desc_field = sp.get("description")
            if isinstance(desc_field, list) and desc_field:
                desc_sid = desc_field[0]
            else:
                desc_sid = desc_field or f"{sid}_description"
            magic_type_sid = sp.get("magicTypeDescription") or ""
            magic_type = tokens.get(magic_type_sid, "")
            mana_per_level = sp.get("manaCost") or []
            # Cooldown rule from in-game: tier N → (N + 1) rounds. Verified
            # against the wiki: tier 1 = 2 rounds, +1 per tier.
            tier = sp.get("rank") or 0
            cooldown = (tier + 1) if tier else None

            out.append({
                "id":         sid,
                "name":       tokens.get(name_sid, sid),
                "icon":       sp.get("icon") or sid,
                "school":     sp.get("school_") or "neutral",
                "tier":       tier,
                "scope":      scope,                      # 'battle' or 'world'
                "magicType":  magic_type,
                "desc":       (tokens.get(desc_sid, "") or "").strip(),
                "manaCost":   list(mana_per_level),
                "cooldown":   cooldown,
                "learnCost":  sp.get("learnCost") or [],
            })
    return out


def build():
    tokens = load_tokens(MAGIC_TOKENS)
    spells = collect_spells(tokens)
    # Sort: school order, then tier, then name
    school_idx = {s: i for i, s in enumerate(SCHOOL_ORDER)}
    spells.sort(key=lambda s: (school_idx.get(s["school"], 99), s["tier"], s["name"]))

    payload = {
        "SPELLS":       spells,
        "SCHOOLS":      [{"id": s, "name": SCHOOL_LABEL[s]} for s in SCHOOL_ORDER],
        "GENERATED_AT": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    js = "/* generated by catalog/scripts/build_spells.py — do not edit by hand */\n"
    js += "window.OE_SPELLS_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"wrote {OUT_JS}  ({len(js):,} bytes)")
    print(f"  total spells: {len(spells)}")
    by_school = {}
    for s in spells:
        by_school[s["school"]] = by_school.get(s["school"], 0) + 1
    for sk, n in sorted(by_school.items()):
        print(f"  {sk}: {n}")


if __name__ == "__main__":
    build()
