"""Emit docs/classes-data.js from catalog/out/classes.json.

The class table holds:
  - Starting stats per class (attack/defence/power/knowledge)
  - Stat-roll probabilities pre/post the level-24 breakpoint
  - 22 skill weights — relative `chance` values the game's level-up roll
    table uses. Probability(skill offered at a roll) = chance / sum(chances).
  - Subclass requirements (already in docs/data.js — duplicate here for the
    builder's quick lookups).

Used by the Hero Builder page.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "catalog" / "out" / "classes.json"
OUT = ROOT / "docs" / "classes-data.js"

# Map (factionId, classType) → display id (already used elsewhere).
DID = {
    ("human",    "might"): "temple",    ("human",    "magic"): "temple",
    ("undead",   "might"): "necropolis",("undead",   "magic"): "necropolis",
    ("nature",   "might"): "grove",     ("nature",   "magic"): "grove",
    ("demon",    "might"): "hive",      ("demon",    "magic"): "hive",
    ("unfrozen", "might"): "schism",    ("unfrozen", "magic"): "schism",
    ("dungeon",  "might"): "dungeon",   ("dungeon",  "magic"): "dungeon",
}

# Subset of skill columns we ship to the builder. Keys match the suffixes the
# game uses on the `*Skill` chance fields below.
SKILL_COLS = [
    # combat
    ("offence",      "Offense",       "combat"),
    ("defence",      "Defense",       "combat"),
    ("resistance",   "Resistance",    "combat"),
    ("battlecraft",  "Battlecraft",   "combat"),
    ("combat",       "Combat",        "combat"),       # might-only
    # magic
    ("sorcery",      "Sorcery",       "magic"),
    ("intelligence", "Wisdom",        "magic"),
    ("summonAvatar", "Summon Avatar", "magic"),
    ("battleMagic",  "Battle Magic",  "magic"),
    ("thaumaturgy",  "Thaumaturgy",   "magic"),        # magic-only
    # schools
    ("daylight",     "Daylight",      "school"),
    ("nightshade",   "Nightshade",    "school"),
    ("arcane",       "Arcane",        "school"),
    ("primal",       "Primal",        "school"),
    # utility
    ("leadership",   "Leadership",    "utility"),
    ("luck",         "Luck",          "utility"),
    ("insight",      "Insight",       "utility"),
    ("diplomacy",    "Diplomacy",     "utility"),
    ("logistics",    "Logistics",     "utility"),
    ("scouting",     "Scouting",      "utility"),
    ("economy",      "Economy",       "utility"),
    ("tactics",      "Tactics",       "utility"),
    ("siegecraft",   "Siegecraft",    "utility"),
    ("recruitment",  "Recruitment",   "utility"),
]


def build():
    src = json.loads(SRC.read_text())
    classes_in = src["heroClasses"]

    classes_out = []
    for c in classes_in:
        display_id = DID[(c["factionId"], c["classType"])]
        out = {
            "name": c["name"],
            "factionId": c["factionId"],
            "displayFaction": display_id,
            "classType": c["classType"],          # 'might' | 'magic'
            "stats": {
                "A": c["attack"],   "D": c["defence"],
                "P": c["power"],    "K": c["knowledge"],
            },
            # Pre/post breakpoint stat-roll probabilities (sum to 1.0 each).
            "rollPre":  {"A": c["attackRollPre24"],  "D": c["defenceRollPre24"],
                         "P": c["powerRollPre24"],   "K": c["knowledgeRollPre24"]},
            "rollPost": {"A": c["attackRollPost24"], "D": c["defenceRollPost24"],
                         "P": c["powerRollPost24"],  "K": c["knowledgeRollPost24"]},
            "breakpoint": c["statsBreakpointLevel"],
            "skills": [
                {"key": key, "name": label, "group": group,
                 "chance": c.get(f"{key}Skill", 0)}
                for key, label, group in SKILL_COLS
            ],
            "factionSkill": c.get("factionSkill") or None,
            "subclasses": c.get("subclasses") or {},
        }
        classes_out.append(out)

    payload = {
        "CLASSES": classes_out,
        "BREAKPOINT": classes_out[0]["breakpoint"] if classes_out else 24,
    }
    js = "/* generated by catalog/scripts/build_classes_data_js.py — do not edit by hand */\n"
    js += "window.OE_CLASSES_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT}  ({len(js):,} bytes; {len(classes_out)} classes)")


if __name__ == "__main__":
    build()
