"""Map templates data — generated multiplayer templates with descriptions
and inferred mode (single-hero / classic / PVE / scenario). The game ships
no per-template preview images in resources.assets, so the page renders
descriptions only (with a generic placeholder icon).

Inputs:
  catalog/raw/Lang/english/texts/ui.json    (templates_description_<id>)
  catalog/raw/DB/quickStart.json            (classicMaps + singleHeroMaps + scenarios)

Output:
  docs/map-templates-data.js  (window.OE_MAP_TEMPLATES_DATA)
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "catalog" / "raw"
OUT_JS = ROOT / "docs" / "map-templates-data.js"


def load_json_strip(path: Path):
    text = path.read_text(encoding="utf-8-sig").lstrip("﻿")
    text = re.sub(r"//[^\n]*", "", text)
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    return json.loads(text)


def load_tokens(path: Path) -> dict[str, str]:
    return {t["sid"]: t["text"] for t in load_json_strip(path).get("tokens", [])}


def title_case_id(tid: str) -> str:
    """Convert e.g. 'jebus_cross' → 'Jebus Cross'."""
    parts = tid.split("_")
    return " ".join(w.capitalize() if w not in ("of", "and", "the") else w for w in parts)


def normalize(s: str) -> str:
    """Normalize a name (lowercased, no spaces/underscores) for matching against quickStart."""
    return re.sub(r"[^a-z0-9]", "", s.lower())


def build():
    ui_tokens = load_tokens(RAW / "Lang" / "english" / "texts" / "ui.json")
    quickStart = load_json_strip(RAW / "DB" / "quickStart.json")

    classic_norms = {normalize(n) for n in quickStart.get("classicMaps", [])}
    single_hero_norms = {normalize(n) for n in quickStart.get("singleHeroMaps", [])}
    scenario_norms = {normalize(n) for n in quickStart.get("scenarios", [])}

    templates = []
    for sid, text in ui_tokens.items():
        m = re.match(r"^templates_description_(.+)$", sid)
        if not m:
            continue
        tid = m.group(1)
        name = title_case_id(tid)
        norm_id = normalize(tid)
        # Strip leading <b>...</b> "Best for singleplayer." marker — we surface
        # mode separately. Keep the rest of the description.
        clean_desc = re.sub(r"^<b>[^<]*</b>\s*", "", text).strip()

        # Determine mode tags
        modes = []
        if tid.startswith("pve_"):
            modes.append("pve")
        if norm_id in classic_norms:
            modes.append("classic")
        if norm_id in single_hero_norms:
            modes.append("single-hero")
        if norm_id in scenario_norms:
            modes.append("scenario")
        # Heuristics for tags not already covered
        if not modes:
            # Heuristic: descriptions mentioning "single hero" / "tournament"
            # → tournament-style multiplayer; everything else → multiplayer
            if "tournament" in clean_desc.lower() or "single hero" in clean_desc.lower():
                modes = ["tournament"]
            else:
                modes = ["multiplayer"]

        # Size heuristic: "scarce" → small, "rich" / "huge" → large, otherwise medium
        d_low = clean_desc.lower()
        if "scarce" in d_low or "small" in d_low or "limited" in d_low or "tiny" in d_low:
            size = "small"
        elif "huge" in d_low or "enormous" in d_low or "massive" in d_low:
            size = "large"
        elif "rich" in d_low or "many areas" in d_low or "multiple" in d_low or "8-player" in d_low:
            size = "large"
        else:
            size = "medium"

        # Player count heuristic: pull "N-player" or "N players"
        players = None
        m_p = re.search(r"(\d+)[-–]?\s*player", clean_desc, re.I)
        if m_p:
            players = int(m_p.group(1))
        elif "two opponents" in d_low or "two enemies" in d_low:
            players = 3
        elif "seven opponents" in d_low:
            players = 8

        templates.append({
            "id":     tid,
            "name":   name,
            "desc":   clean_desc,
            "modes":  modes,
            "size":   size,
            "playerCount": players,
        })
    templates.sort(key=lambda t: t["name"])

    payload = {
        "TEMPLATES":    templates,
        "GENERATED_AT": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    js = "/* generated by catalog/scripts/build_map_templates.py — do not edit by hand */\n"
    js += "window.OE_MAP_TEMPLATES_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"wrote {OUT_JS}  ({len(js):,} bytes)")
    print(f"  {len(templates)} templates")
    by_mode = {}
    for t in templates:
        for m in t["modes"]:
            by_mode[m] = by_mode.get(m, 0) + 1
    for m, n in sorted(by_mode.items()):
        print(f"  mode={m:14s} {n}")


if __name__ == "__main__":
    build()
