"""Resources data — every resource type the game tracks.

Standard 6 + Dust + Graal. Pulls names from mapObjects.json (resource_<key>_*
tokens) and falls back to ui.json for the few not in mapObjects (e.g. graal).
Icons live in resources.assets under the bare resource id.

Output:
  docs/resources-data.js  (window.OE_RESOURCES_DATA)
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "catalog" / "raw"
OUT_JS = ROOT / "docs" / "resources-data.js"


def load_tokens(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8-sig").lstrip("﻿")
    text = re.sub(r"//[^\n]*", "", text); text = re.sub(r",(\s*[}\]])", r"\1", text)
    return {t["sid"]: t["text"] for t in json.loads(text).get("tokens", [])}


# Display order — by category, with primary 4 first, then rare 3, then dust + graal.
RESOURCE_ORDER = [
    ("gold",     "primary"),
    ("wood",     "primary"),
    ("ore",      "primary"),
    ("gemstones","rare"),
    ("crystals", "rare"),
    ("mercury",  "rare"),
    ("dust",     "special"),
    ("graal",    "special"),
]

CATEGORY_LABEL = {
    "primary": "Primary resources (every faction)",
    "rare":    "Rare resources (faction-specific economy)",
    "special": "Special resources",
}

# Brief tournament-relevant context for each resource (editorial).
TACTICAL_NOTES = {
    "gold":     "The most-spent resource. Recruitment, building, market trades all key on gold. Banks, Treasuries and Merchants Guild law are the standard income levers.",
    "wood":     "Fortifications, dwellings, Mage Guilds, walls. The most consumed primary outside gold.",
    "ore":      "Fortifications and most dwellings need ore. Dungeon's *Or No Ore?* law (-40% ore) is the relief valve when you're rushing T2 walls.",
    "gemstones":"Mid-tier dwellings + Mage Guild upgrades. Each faction has its own native rare resource that unlocks early; the other two come slower.",
    "crystals": "Mid-to-late dwellings + Mage Guild upgrades. Schism is uniquely crystal-hungry due to its tech tree.",
    "mercury":  "Mage Guild rolls + spell upgrades + late-tier units. *Mining: Mercury* law gives extra income but is rarely the priority.",
    "dust":     "Used at the Alchemist's Laboratory to upgrade artifacts and unlock additional spells in the Magic Observatory. Comes from quests and certain map objects.",
    "graal":    "One-of-a-kind. Built into the Graal slot to unlock a city's signature super-building (Golden Calf, etc.).",
}


def build():
    map_obj_tokens = load_tokens(RAW / "Lang" / "english" / "texts" / "mapObjects.json")
    ui_tokens      = load_tokens(RAW / "Lang" / "english" / "texts" / "ui.json")

    resources = []
    for rid, category in RESOURCE_ORDER:
        # Try resource_<id>_name first (mapObjects), then <id>_name (ui)
        name = (map_obj_tokens.get(f"resource_{rid}_name")
                or ui_tokens.get(f"{rid}_name")
                or rid.title())
        desc = (map_obj_tokens.get(f"resource_{rid}_description") or "").strip()
        narrative = (map_obj_tokens.get(f"resource_{rid}_narrativeDescription") or "").strip()
        # Strip {0} placeholders from desc since we don't have a context-bound value
        desc = re.sub(r"\{[0-9]+\}", "?", desc) if desc else ""
        resources.append({
            "id":         rid,
            "name":       name,
            "category":   category,
            "desc":       desc,
            "narrative":  narrative,
            "tactical":   TACTICAL_NOTES.get(rid, ""),
        })

    payload = {
        "RESOURCES":      resources,
        "CATEGORY_LABEL": CATEGORY_LABEL,
        "GENERATED_AT":   datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    js = "/* generated by catalog/scripts/build_resources.py — do not edit by hand */\n"
    js += "window.OE_RESOURCES_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"wrote {OUT_JS}  ({len(js):,} bytes)")
    print(f"  {len(resources)} resources")


if __name__ == "__main__":
    build()
